x-icinga2: &x-icinga2
  image: icinga/icinga2

volumes:
  master1: { }
  master2: { }

services:
  master1:
    <<: *x-icinga2
    hostname: master1
    command:
      - /scripts/node-setup.sh
      - /scripts/configure.sh
      - icinga2
      - daemon
    volumes:
      - ./scripts:/scripts:ro
      - ./config:/config:ro
      - master1:/data

  master2:
    <<: *x-icinga2
    hostname: master2
    command:
      - /scripts/await-ca.sh
      - /scripts/node-setup.sh
      - /scripts/configure.sh
      - icinga2
      - daemon
    volumes:
      - ./scripts:/scripts:ro
      - ./config:/config:ro
      - master2:/data
      - master1:/ca:ro

  agent:
    <<: *x-icinga2
    deploy:
      replicas: 7
    command:
      - /scripts/await-ca.sh
      - /scripts/node-setup.sh
      - /scripts/configure.sh
      - icinga2
      - daemon
    volumes:
      - ./scripts:/scripts:ro
      - ./config:/config:ro
      - master1:/ca:ro
